version: '3.1'
services:
  stats-service:
    build: ./stats/stats-service
    image: stats-service
    container_name: stats-service
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stat
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    environment:
      - POSTGRES_DB=ewm-statistic
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  ewm-service:
    image: main
    build: main
    ports:
       - "8080:8080"
    depends_on:
       - ewm-db
       - stats-service
    environment:
       - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
       - SPRING_DATASOURCE_USERNAME=ewm
       - SPRING_DATASOURCE_PASSWORD=ewm

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    environment:
    - POSTGRES_DB=ewm
    - POSTGRES_USER=ewm
    - POSTGRES_PASSWORD=ewm
